name: Publish artifacts
on:
  push:
    branches:
      - prod
      - stage
      - dev
      - feature/*
      - bugfix/*
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew --build-cache assemble
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: Checkstyle
        run: ./gradlew checkstyleMain
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: Publish
        run: ./gradlew publish
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Trigger ${{ steps.extract_branch.outputs.branch }} image build
        if: ${{ steps.extract_branch.outputs.branch == 'prod' || steps.extract_branch.outputs.branch == 'stage' }}
        run: |
          curl -XPOST -u "${{ secrets.githubUsername }}:${{ secrets.githubToken }}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/playlegend/LegendServer/dispatches --data '{"event_type": "build_images", "client_payload": { "branch": "${{steps.extract_branch.outputs.branch}}"}}'
